-- =====================================================================
-- 20260630000400_fill_tarot_deckaura.sql
-- Deckaura tarot meanings (per project sources doc: MIT primary base layer)
-- Source: deckaura.com  (tarot_card_meanings.csv, all 78 cards 0-77)
-- Fills: upright_core, reversed_core, upright_love, upright_career,
--        upright_yes_no, correspondence_seed (zodiac, majors only)
-- Minor-arcana astro lives in the decans table (authored Golden Dawn bridge).
-- Keyed on card_number. Idempotent.
-- =====================================================================

begin;
update tarot_cards set upright_core='New beginnings, innocence, adventure, free spirit', reversed_core='Recklessness, fear of change, holding back', upright_love='Exciting new romance, spontaneous love', upright_career='New career path, leap of faith', upright_yes_no='Yes', correspondence_seed='Uranus' where card_number=0;
update tarot_cards set upright_core='Manifestation, willpower, resourcefulness', reversed_core='Manipulation, poor planning, untapped talents', upright_love='Magnetic attraction, confident pursuit', upright_career='Skill mastery, new opportunity', upright_yes_no='Yes', correspondence_seed='Mercury' where card_number=1;
update tarot_cards set upright_core='Intuition, mystery, inner wisdom, subconscious', reversed_core='Secrets, disconnection from intuition', upright_love='Hidden feelings, trust your instincts', upright_career='Follow your gut, hidden knowledge', upright_yes_no='Yes', correspondence_seed='Moon' where card_number=2;
update tarot_cards set upright_core='Abundance, nurturing, fertility, beauty', reversed_core='Insecurity, neglect, creative block', upright_love='Deep love, sensual connection', upright_career='Growth, prosperity, creative success', upright_yes_no='Yes', correspondence_seed='Venus' where card_number=3;
update tarot_cards set upright_core='Authority, structure, leadership, stability', reversed_core='Domination, rigidity, lack of discipline', upright_love='Committed partner, protective love', upright_career='Leadership role, promotion', upright_yes_no='Yes', correspondence_seed='Aries' where card_number=4;
update tarot_cards set upright_core='Tradition, spiritual guidance, conformity', reversed_core='Rebellion, subversion, new approaches', upright_love='Traditional relationship, commitment', upright_career='Mentorship, conventional path', upright_yes_no='Yes', correspondence_seed='Taurus' where card_number=5;
update tarot_cards set upright_core='Love, choices, partnerships, harmony', reversed_core='Disharmony, imbalance, misalignment', upright_love='Soulmate connection, deep bond', upright_career='Important partnership, career choice', upright_yes_no='Yes', correspondence_seed='Gemini' where card_number=6;
update tarot_cards set upright_core='Determination, willpower, triumph, control', reversed_core='Lack of direction, aggression', upright_love='Pursuing love with confidence', upright_career='Ambition, career victory', upright_yes_no='Yes', correspondence_seed='Cancer' where card_number=7;
update tarot_cards set upright_core='Courage, patience, inner strength, compassion', reversed_core='Self-doubt, weakness, insecurity', upright_love='Patient love, gentle strength', upright_career='Perseverance, overcoming challenges', upright_yes_no='Yes', correspondence_seed='Leo' where card_number=8;
update tarot_cards set upright_core='Introspection, solitude, inner guidance', reversed_core='Isolation, loneliness, withdrawal', upright_love='Self-discovery before love', upright_career='Career reflection, finding purpose', upright_yes_no='Maybe', correspondence_seed='Virgo' where card_number=9;
update tarot_cards set upright_core='Cycles, destiny, turning points, luck', reversed_core='Bad luck, resistance to change', upright_love='Fated romance, relationship shift', upright_career='Career change, unexpected opportunity', upright_yes_no='Yes', correspondence_seed='Jupiter' where card_number=10;
update tarot_cards set upright_core='Fairness, truth, accountability, law', reversed_core='Unfairness, dishonesty, lack of accountability', upright_love='Fair partnership, karmic relationship', upright_career='Legal matters, ethical decisions', upright_yes_no='Yes', correspondence_seed='Libra' where card_number=11;
update tarot_cards set upright_core='Surrender, new perspective, pause, letting go', reversed_core='Stalling, resistance, indecision', upright_love='Pause in relationship, new viewpoint', upright_career='Career pause, seeing things differently', upright_yes_no='Maybe', correspondence_seed='Neptune' where card_number=12;
update tarot_cards set upright_core='Transformation, endings, new beginnings, change', reversed_core='Resistance to change, stagnation', upright_love='Relationship transformation, letting go', upright_career='Career ending leading to new start', upright_yes_no='Maybe', correspondence_seed='Scorpio' where card_number=13;
update tarot_cards set upright_core='Balance, patience, moderation, purpose', reversed_core='Imbalance, excess, lack of patience', upright_love='Balanced relationship, harmony', upright_career='Work-life balance, patience pays off', upright_yes_no='Yes', correspondence_seed='Sagittarius' where card_number=14;
update tarot_cards set upright_core='Addiction, materialism, shadow self, bondage', reversed_core='Breaking free, releasing limiting beliefs', upright_love='Toxic attachment, passion without depth', upright_career='Feeling trapped in job, materialism', upright_yes_no='No', correspondence_seed='Capricorn' where card_number=15;
update tarot_cards set upright_core='Sudden change, upheaval, revelation, chaos', reversed_core='Avoiding disaster, fear of change', upright_love='Relationship shakeup, revelation', upright_career='Sudden job loss, unexpected upheaval', upright_yes_no='No', correspondence_seed='Mars' where card_number=16;
update tarot_cards set upright_core='Hope, renewal, spirituality, inspiration', reversed_core='Despair, lack of faith, disconnection', upright_love='Healing love, renewed hope', upright_career='Creative inspiration, dream career', upright_yes_no='Yes', correspondence_seed='Aquarius' where card_number=17;
update tarot_cards set upright_core='Illusion, fear, subconscious, anxiety', reversed_core='Release of fear, clarity emerging', upright_love='Confusion in love, hidden emotions', upright_career='Uncertainty, trust your intuition', upright_yes_no='Maybe', correspondence_seed='Pisces' where card_number=18;
update tarot_cards set upright_core='Joy, success, vitality, positivity', reversed_core='Temporary sadness, lack of clarity', upright_love='Happy relationship, joy in love', upright_career='Career success, recognition', upright_yes_no='Yes', correspondence_seed='Sun' where card_number=19;
update tarot_cards set upright_core='Rebirth, reflection, reckoning, absolution', reversed_core='Self-doubt, refusal to learn', upright_love='Relationship evaluation, second chance', upright_career='Career calling, important decision', upright_yes_no='Yes', correspondence_seed='Pluto' where card_number=20;
update tarot_cards set upright_core='Completion, accomplishment, travel, wholeness', reversed_core='Incompletion, shortcuts, delays', upright_love='Fulfilled relationship, soulmate found', upright_career='Goal achieved, career milestone', upright_yes_no='Yes', correspondence_seed='Saturn' where card_number=21;
update tarot_cards set upright_core='Inspiration, new venture, potential, creation', reversed_core='Delays, lack of motivation, hesitation', upright_love='Exciting new attraction, passion', upright_career='New business idea, creative spark', upright_yes_no='Yes', correspondence_seed='' where card_number=22;
update tarot_cards set upright_core='Planning, future vision, decisions, discovery', reversed_core='Fear of unknown, lack of planning', upright_love='Choosing between partners, planning future', upright_career='Business planning, expanding horizons', upright_yes_no='Yes', correspondence_seed='' where card_number=23;
update tarot_cards set upright_core='Expansion, foresight, overseas opportunities', reversed_core='Delays, obstacles, frustration', upright_love='Long-distance love, growth together', upright_career='Business expansion, international work', upright_yes_no='Yes', correspondence_seed='' where card_number=24;
update tarot_cards set upright_core='Celebration, homecoming, harmony, community', reversed_core='Lack of harmony, transition, instability', upright_love='Engagement, wedding, happy home', upright_career='Team success, work celebration', upright_yes_no='Yes', correspondence_seed='' where card_number=25;
update tarot_cards set upright_core='Conflict, competition, tension, disagreement', reversed_core='Avoiding conflict, inner conflict', upright_love='Arguments, competition for attention', upright_career='Workplace rivalry, creative differences', upright_yes_no='No', correspondence_seed='' where card_number=26;
update tarot_cards set upright_core='Victory, recognition, success, public acclaim', reversed_core='Fall from grace, ego, lack of recognition', upright_love='Public commitment, admired relationship', upright_career='Promotion, public recognition', upright_yes_no='Yes', correspondence_seed='' where card_number=27;
update tarot_cards set upright_core='Defensiveness, perseverance, standing ground', reversed_core='Giving up, overwhelmed, exhaustion', upright_love='Defending your relationship, boundaries', upright_career='Protecting your position, competition', upright_yes_no='Maybe', correspondence_seed='' where card_number=28;
update tarot_cards set upright_core='Speed, movement, quick progress, travel', reversed_core='Delays, frustration, waiting', upright_love='Fast-moving romance, exciting news', upright_career='Rapid career progress, travel for work', upright_yes_no='Yes', correspondence_seed='' where card_number=29;
update tarot_cards set upright_core='Resilience, courage, persistence, last stand', reversed_core='Exhaustion, giving up, overwhelmed', upright_love='Guarded heart, persisting through tough times', upright_career='Almost there, don''t give up', upright_yes_no='Maybe', correspondence_seed='' where card_number=30;
update tarot_cards set upright_core='Burden, responsibility, hard work, stress', reversed_core='Delegation, release, breakdown', upright_love='Carrying relationship burden alone', upright_career='Overworked, need to delegate', upright_yes_no='No', correspondence_seed='' where card_number=31;
update tarot_cards set upright_core='Enthusiasm, exploration, discovery, free spirit', reversed_core='Lack of direction, setbacks, procrastination', upright_love='Exciting new crush, flirtatious energy', upright_career='New creative project, learning opportunity', upright_yes_no='Yes', correspondence_seed='' where card_number=32;
update tarot_cards set upright_core='Energy, passion, adventure, impulsiveness', reversed_core='Haste, scattered energy, delays', upright_love='Passionate but short-lived romance', upright_career='Quick action, travel for career', upright_yes_no='Yes', correspondence_seed='' where card_number=33;
update tarot_cards set upright_core='Confidence, determination, joy, vibrancy', reversed_core='Selfishness, jealousy, demanding', upright_love='Charismatic partner, warm love', upright_career='Leadership, confident business woman', upright_yes_no='Yes', correspondence_seed='' where card_number=34;
update tarot_cards set upright_core='Leadership, vision, entrepreneur, honor', reversed_core='Impulsiveness, overbearing, vicious', upright_love='Bold romantic gestures, passionate partner', upright_career='Business leader, bold decisions', upright_yes_no='Yes', correspondence_seed='' where card_number=35;
update tarot_cards set upright_core='New love, emotional beginning, compassion', reversed_core='Emotional loss, blocked feelings, emptiness', upright_love='New relationship, deep emotional connection', upright_career='Creative fulfillment, emotional satisfaction', upright_yes_no='Yes', correspondence_seed='' where card_number=36;
update tarot_cards set upright_core='Partnership, mutual attraction, unity', reversed_core='Breakup, imbalance, disharmony', upright_love='Mutual love, equal partnership', upright_career='Business partnership, collaboration', upright_yes_no='Yes', correspondence_seed='' where card_number=37;
update tarot_cards set upright_core='Celebration, friendship, joy, community', reversed_core='Overindulgence, gossip, isolation', upright_love='Social love, friends becoming lovers', upright_career='Team celebration, networking success', upright_yes_no='Yes', correspondence_seed='' where card_number=38;
update tarot_cards set upright_core='Apathy, contemplation, missed opportunities', reversed_core='Awareness, acceptance, motivation returning', upright_love='Taking love for granted, emotional boredom', upright_career='Disengagement, overlooking opportunity', upright_yes_no='No', correspondence_seed='' where card_number=39;
update tarot_cards set upright_core='Loss, grief, regret, disappointment', reversed_core='Acceptance, moving on, finding peace', upright_love='Heartbreak, mourning lost love', upright_career='Career disappointment, focusing on loss', upright_yes_no='No', correspondence_seed='' where card_number=40;
update tarot_cards set upright_core='Nostalgia, childhood, innocence, reunion', reversed_core='Moving forward, leaving the past', upright_love='Reconnecting with ex, childhood sweetheart', upright_career='Past career returning, nostalgia', upright_yes_no='Yes', correspondence_seed='' where card_number=41;
update tarot_cards set upright_core='Fantasy, illusion, choices, wishful thinking', reversed_core='Clarity, focus, making a decision', upright_love='Unrealistic expectations in love', upright_career='Too many options, need to focus', upright_yes_no='Maybe', correspondence_seed='' where card_number=42;
update tarot_cards set upright_core='Walking away, searching for meaning, withdrawal', reversed_core='Fear of change, stagnation, clinging', upright_love='Leaving unfulfilling relationship', upright_career='Quitting job to find purpose', upright_yes_no='Maybe', correspondence_seed='' where card_number=43;
update tarot_cards set upright_core='Wish fulfillment, satisfaction, contentment', reversed_core='Dissatisfaction, greed, unfulfillment', upright_love='Relationship wishes coming true', upright_career='Career satisfaction, goals achieved', upright_yes_no='Yes', correspondence_seed='' where card_number=44;
update tarot_cards set upright_core='Happiness, harmony, family, emotional fulfillment', reversed_core='Broken home, disharmony, misalignment', upright_love='Happy marriage, family bliss', upright_career='Dream career, work-life harmony', upright_yes_no='Yes', correspondence_seed='' where card_number=45;
update tarot_cards set upright_core='Creative message, intuition, inner child', reversed_core='Emotional immaturity, creative block', upright_love='Sweet romantic gesture, new love message', upright_career='Creative opportunity, artistic pursuit', upright_yes_no='Yes', correspondence_seed='' where card_number=46;
update tarot_cards set upright_core='Romance, charm, imagination, beauty', reversed_core='Moodiness, unrealistic, jealousy', upright_love='Romantic proposal, charming partner', upright_career='Following creative passion, artistic career', upright_yes_no='Yes', correspondence_seed='' where card_number=47;
update tarot_cards set upright_core='Compassion, calm, intuitive, nurturing', reversed_core='Insecurity, co-dependency, emotional manipulation', upright_love='Deeply caring partner, empathic love', upright_career='Counseling career, emotional intelligence', upright_yes_no='Yes', correspondence_seed='' where card_number=48;
update tarot_cards set upright_core='Emotional balance, diplomacy, calm authority', reversed_core='Emotional manipulation, moodiness', upright_love='Wise loving partner, emotional maturity', upright_career='Leadership through empathy, diplomacy', upright_yes_no='Yes', correspondence_seed='' where card_number=49;
update tarot_cards set upright_core='Clarity, breakthrough, truth, new idea', reversed_core='Confusion, chaos, lack of clarity', upright_love='Clear communication in love', upright_career='Breakthrough idea, mental clarity', upright_yes_no='Yes', correspondence_seed='' where card_number=50;
update tarot_cards set upright_core='Indecision, stalemate, blocked emotions', reversed_core='Information overload, overwhelm, clarity coming', upright_love='Relationship crossroads, avoiding truth', upright_career='Career decision paralysis', upright_yes_no='Maybe', correspondence_seed='' where card_number=51;
update tarot_cards set upright_core='Heartbreak, sorrow, grief, painful truth', reversed_core='Recovery, healing, forgiveness', upright_love='Breakup, betrayal, emotional pain', upright_career='Job loss, painful professional truth', upright_yes_no='No', correspondence_seed='' where card_number=52;
update tarot_cards set upright_core='Rest, recovery, contemplation, restoration', reversed_core='Restlessness, burnout, lack of rest', upright_love='Relationship pause, time to reflect', upright_career='Vacation needed, recovery from stress', upright_yes_no='Maybe', correspondence_seed='' where card_number=53;
update tarot_cards set upright_core='Conflict, defeat, win at all costs, betrayal', reversed_core='Reconciliation, forgiveness, moving on', upright_love='Arguments, power struggles in love', upright_career='Office politics, unfair competition', upright_yes_no='No', correspondence_seed='' where card_number=54;
update tarot_cards set upright_core='Transition, moving on, recovery, travel', reversed_core='Stagnation, resistance, unfinished business', upright_love='Moving on from heartbreak', upright_career='Career transition, relocation', upright_yes_no='Yes', correspondence_seed='' where card_number=55;
update tarot_cards set upright_core='Deception, strategy, stealth, cunning', reversed_core='Coming clean, confession, conscience', upright_love='Dishonesty in relationship, secrets', upright_career='Underhanded work tactics, be careful', upright_yes_no='No', correspondence_seed='' where card_number=56;
update tarot_cards set upright_core='Restriction, trapped, self-limiting beliefs', reversed_core='Freedom, release, new perspective', upright_love='Feeling trapped in relationship', upright_career='Feeling stuck in career, self-imposed limits', upright_yes_no='No', correspondence_seed='' where card_number=57;
update tarot_cards set upright_core='Anxiety, worry, nightmares, fear', reversed_core='Hope, recovery, reaching out for help', upright_love='Relationship anxiety, overthinking', upright_career='Work stress, insomnia from career worry', upright_yes_no='No', correspondence_seed='' where card_number=58;
update tarot_cards set upright_core='Endings, betrayal, rock bottom, crisis', reversed_core='Recovery, regeneration, rising up', upright_love='Painful breakup, hitting rock bottom', upright_career='Career collapse, time to rebuild', upright_yes_no='No', correspondence_seed='' where card_number=59;
update tarot_cards set upright_core='Curiosity, restlessness, mental energy', reversed_core='Deception, manipulation, all talk', upright_love='Curious about love, overthinking feelings', upright_career='New ideas, research, mental exploration', upright_yes_no='Yes', correspondence_seed='' where card_number=60;
update tarot_cards set upright_core='Ambition, action, impulsiveness, fast thinking', reversed_core='No direction, disregard, aggression', upright_love='Rushing into love, intense pursuit', upright_career='Aggressive career moves, quick action', upright_yes_no='Yes', correspondence_seed='' where card_number=61;
update tarot_cards set upright_core='Independence, clear boundaries, direct communication', reversed_core='Cold, cruel, bitterness', upright_love='Independent partner, honest communication', upright_career='Clear leadership, objective decisions', upright_yes_no='Yes', correspondence_seed='' where card_number=62;
update tarot_cards set upright_core='Intellectual power, authority, truth, ethics', reversed_core='Manipulation, tyranny, abuse of power', upright_love='Logical partner, clear communication', upright_career='Authority figure, legal expertise', upright_yes_no='Yes', correspondence_seed='' where card_number=63;
update tarot_cards set upright_core='New opportunity, prosperity, abundance', reversed_core='Missed opportunity, scarcity, instability', upright_love='New stable relationship beginning', upright_career='New job, financial opportunity', upright_yes_no='Yes', correspondence_seed='' where card_number=64;
update tarot_cards set upright_core='Balance, adaptability, juggling priorities', reversed_core='Imbalance, disorganization, overwhelm', upright_love='Balancing love and life, juggling priorities', upright_career='Work-life balance, managing multiple projects', upright_yes_no='Maybe', correspondence_seed='' where card_number=65;
update tarot_cards set upright_core='Teamwork, collaboration, skill, craftsmanship', reversed_core='Lack of teamwork, disorganization, conflict', upright_love='Building relationship together, shared goals', upright_career='Team project, skill recognition', upright_yes_no='Yes', correspondence_seed='' where card_number=66;
update tarot_cards set upright_core='Security, control, conservation, stability', reversed_core='Greed, materialism, self-protection', upright_love='Possessiveness, fear of vulnerability', upright_career='Financial security, holding onto resources', upright_yes_no='Maybe', correspondence_seed='' where card_number=67;
update tarot_cards set upright_core='Hardship, loss, isolation, feeling left out', reversed_core='Recovery, improvement, turning corner', upright_love='Loneliness, feeling rejected in love', upright_career='Financial hardship, job loss', upright_yes_no='No', correspondence_seed='' where card_number=68;
update tarot_cards set upright_core='Generosity, charity, sharing wealth, balance', reversed_core='Debt, selfishness, strings attached', upright_love='Generous partner, giving and receiving love', upright_career='Raise, bonus, charitable giving', upright_yes_no='Yes', correspondence_seed='' where card_number=69;
update tarot_cards set upright_core='Patience, long-term view, investment, perseverance', reversed_core='Impatience, lack of reward, wasted effort', upright_love='Patience in love, long-term investment', upright_career='Career growth takes time, be patient', upright_yes_no='Maybe', correspondence_seed='' where card_number=70;
update tarot_cards set upright_core='Craftsmanship, skill development, diligence', reversed_core='Perfectionism, lack of ambition, mediocrity', upright_love='Working on relationship, improving together', upright_career='Skill building, apprenticeship, hard work', upright_yes_no='Yes', correspondence_seed='' where card_number=71;
update tarot_cards set upright_core='Abundance, luxury, self-sufficiency, independence', reversed_core='Over-investment in work, superficiality', upright_love='Enjoying being single, self-love', upright_career='Financial independence, enjoying success', upright_yes_no='Yes', correspondence_seed='' where card_number=72;
update tarot_cards set upright_core='Wealth, legacy, family, inheritance, establishment', reversed_core='Financial failure, family disputes', upright_love='Long-lasting love, family wealth', upright_career='Financial success, family business', upright_yes_no='Yes', correspondence_seed='' where card_number=73;
update tarot_cards set upright_core='Ambition, studiousness, new financial opportunity', reversed_core='Lack of progress, procrastination', upright_love='Steady new romance, building foundations', upright_career='Scholarship, new job, study opportunity', upright_yes_no='Yes', correspondence_seed='' where card_number=74;
update tarot_cards set upright_core='Reliability, hard work, routine, patience', reversed_core='Boredom, laziness, feeling stuck', upright_love='Loyal steady partner, slow romance', upright_career='Reliable worker, methodical approach', upright_yes_no='Yes', correspondence_seed='' where card_number=75;
update tarot_cards set upright_core='Nurturing, practical, financial security, homebody', reversed_core='Neglect, smothering, work-home imbalance', upright_love='Caring partner, domestic happiness', upright_career='Successful businesswoman, practical leader', upright_yes_no='Yes', correspondence_seed='' where card_number=76;
update tarot_cards set upright_core='Wealth, business, leadership, security, discipline', reversed_core='Greed, indulgence, materialism', upright_love='Stable provider, secure relationship', upright_career='Business success, financial mastery', upright_yes_no='Yes', correspondence_seed='' where card_number=77;
commit;

-- verify: all 78 should report filled
-- select count(upright_core), count(upright_love), count(upright_yes_no) from tarot_cards;
